### ISSUE TITLE
Unable to find the Live token in skype-http

### ISSUE THREAD

**Issue by devk1d** [Toxblh/skype-to-telegram#4]
Unable to find the Live token in skype-http

**Comment by Toxblh** [comment]
Remember!
First of all, you need to login here - https://www.skype.com/en/features/skype-web/ and right top corner click on My Account will be a question about security - bla bla bla, is it looks good or not account details like email and phone number. 
Yes, I receive it sometime as well.

**Comment by Toxblh** [comment]
It's shouldn't change! It should be your, lib and me don't change anything, is just a security attention reminder from Microsoft

**Comment by devk1d** [comment]
I mean i can't login skype account. here is the log

```
skype-bot_1  | (node:1) UnhandledPromiseRejectionWarning: MicrosoftAccountLogin: Unable to login with MicrosoftAccount.
skype-bot_1  |   caused by GetLiveToken: Unable to get the Live token for Skype
skype-bot_1  |   caused by LiveTokenNotFound: Unable to find the Live token. This token is normally found in the HTML response as the value of the element with the id "t". This error may be caused by a change in the Microsoft login workflow. HTML page: "<html><head><noscript>JavaScript required to sign in<meta http-equiv=\"Refresh\" content=\"0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033&uaid=4b7fc6b9b8db4398bcfe40ca150036f4&client_flight=ReservedFlight33,ReservedFligh\"/></noscript><title>Continue</title><script type=\"text/javascript\">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload=\"javascript:DoSubmit();\"><form name=\"fmHF\" id=\"fmHF\" action=\"https://account.live.com/identity/confirm?mkt=EN-US&uiflavor=web&id=293290&ru=https://login.live.com/login.srf%3fid%3d293290%26opid%3d969D180A49C49868%26opidt%3d1578037537\" method=\"post\" target=\"_top\"><input type=\"hidden\" name=\"client_flight\" id=\"client_flight\" value=\"ReservedFlight33,ReservedFligh\"><input type=\"hidden\" name=\"ipt\" id=\"ipt\" value=\"DaUsjHPJXn0ost7zJ43!EqHz!l039aM0Y!QQL!ScEXsV3xVcPcjtFUsNeJyJEnHOm32YSnOCB9KVKBB5jJB6NZmbEHLUp1eFRiHUbN1!0O0tt2vywBq8ILQYCe7uVw3JHWSOex5wF1wErWkZn3GuK06sVd7mxQrbvEuBeK5o!jctyQnlvyynqNb*Y*uJVYlX4PJ!shDUrKkRHLLdQexTAFc6mPn9U85XCr8rSu3F8yL8jxM7Dv8qnXcRd3jMxEtfFiBvpJoGoaTz6TxKDaXjPI*B3CXCbDt2GA7*zLJa8jMCF3Ii44L8rwj8qreRhvtoFttgtkV*TZfCnown5H4A348RuGU24zkv6bAlv*zQU!7zysikFxvD0rDwjJ1m*ucd4v7qn4Hjn5gMx!HIs1Y5AONp!ymY5jz3U82VEORu2VbM2gz7xMZvDZODppEROqtEzOofagYtcjAp0Zl5qiro9ik$\"><input type=\"hidden\" name=\"pprid\" id=\"pprid\" value=\"a071e481491d5018\"><input type=\"hidden\" name=\"uaid\" id=\"uaid\" value=\"4b7fc6b9b8db4398bcfe40ca150036f4\"></form></body></html>"
skype-bot_1  |     at Object.create (/code/node_modules/skype-http/errors/microsoft-account/get-live-token.js:17:16)
skype-bot_1  |     at scrapLiveToken (/code/node_modules/skype-http/providers/microsoft-account.js:216:61)
skype-bot_1  |     at getLiveToken (/code/node_modules/skype-http/providers/microsoft-account.js:138:16)
skype-bot_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
skype-bot_1  |     at async Object.login (/code/node_modules/skype-http/providers/microsoft-account.js:31:27)
skype-bot_1  |     at async Object.login (/code/node_modules/skype-http/login.js:36:24)
skype-bot_1  |     at async Object.connect (/code/node_modules/skype-http/connect.js:28:22)
skype-bot_1  |     at async initSkype (/code/dist/index.js:108:11)
skype-bot_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
skype-bot_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
skype-bot_1  | error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 401 Unauthorized"}
```

**Comment by Toxblh** [comment]
Just do it what I say, and try again

**Comment by Toxblh** [comment]
This because lib opens the site and login to account. And receive unpromised answer with security question. I do not author the lib.

**Comment by CharlesNjau** [comment]
> I mean i can't login skype account. here is the logs
> 
> ```
> skype-bot_1  | (node:1) UnhandledPromiseRejectionWarning: MicrosoftAccountLogin: Unable to login with MicrosoftAccount.
> skype-bot_1  |   caused by GetLiveToken: Unable to get the Live token for Skype
> skype-bot_1  |   caused by LiveTokenNotFound: Unable to find the Live token. This token is normally found in the HTML response as the value of the element with the id "t". This error may be caused by a change in the Microsoft login workflow. HTML page: "<html><head><noscript>JavaScript required to sign in<meta http-equiv=\"Refresh\" content=\"0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033&uaid=4b7fc6b9b8db4398bcfe40ca150036f4&client_flight=ReservedFlight33,ReservedFligh\"/></noscript><title>Continue</title><script type=\"text/javascript\">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload=\"javascript:DoSubmit();\"><form name=\"fmHF\" id=\"fmHF\" action=\"https://account.live.com/identity/confirm?mkt=EN-US&uiflavor=web&id=293290&ru=https://login.live.com/login.srf%3fid%3d293290%26opid%3d969D180A49C49868%26opidt%3d1578037537\" method=\"post\" target=\"_top\"><input type=\"hidden\" name=\"client_flight\" id=\"client_flight\" value=\"ReservedFlight33,ReservedFligh\"><input type=\"hidden\" name=\"ipt\" id=\"ipt\" value=\"DaUsjHPJXn0ost7zJ43!EqHz!l039aM0Y!QQL!ScEXsV3xVcPcjtFUsNeJyJEnHOm32YSnOCB9KVKBB5jJB6NZmbEHLUp1eFRiHUbN1!0O0tt2vywBq8ILQYCe7uVw3JHWSOex5wF1wErWkZn3GuK06sVd7mxQrbvEuBeK5o!jctyQnlvyynqNb*Y*uJVYlX4PJ!shDUrKkRHLLdQexTAFc6mPn9U85XCr8rSu3F8yL8jxM7Dv8qnXcRd3jMxEtfFiBvpJoGoaTz6TxKDaXjPI*B3CXCbDt2GA7*zLJa8jMCF3Ii44L8rwj8qreRhvtoFttgtkV*TZfCnown5H4A348RuGU24zkv6bAlv*zQU!7zysikFxvD0rDwjJ1m*ucd4v7qn4Hjn5gMx!HIs1Y5AONp!ymY5jz3U82VEORu2VbM2gz7xMZvDZODppEROqtEzOofagYtcjAp0Zl5qiro9ik$\"><input type=\"hidden\" name=\"pprid\" id=\"pprid\" value=\"a071e481491d5018\"><input type=\"hidden\" name=\"uaid\" id=\"uaid\" value=\"4b7fc6b9b8db4398bcfe40ca150036f4\"></form></body></html>"
> skype-bot_1  |     at Object.create (/code/node_modules/skype-http/errors/microsoft-account/get-live-token.js:17:16)
> skype-bot_1  |     at scrapLiveToken (/code/node_modules/skype-http/providers/microsoft-account.js:216:61)
> skype-bot_1  |     at getLiveToken (/code/node_modules/skype-http/providers/microsoft-account.js:138:16)
> skype-bot_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> skype-bot_1  |     at async Object.login (/code/node_modules/skype-http/providers/microsoft-account.js:31:27)
> skype-bot_1  |     at async Object.login (/code/node_modules/skype-http/login.js:36:24)
> skype-bot_1  |     at async Object.connect (/code/node_modules/skype-http/connect.js:28:22)
> skype-bot_1  |     at async initSkype (/code/dist/index.js:108:11)
> skype-bot_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> skype-bot_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> skype-bot_1  | error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 401 Unauthorized"}
> ```

I think your issue stems from the fact you can get refresh token from skype the token usally lasts a whole day and is restricted to one device only thats what i have observed so far i logged in and tried it on my local host it worked fine but when i deployed to the server it didn't because my current session hasn't yet expired so when i tried the next day it worked after my session had expired this is only valid for skype web
